@startgantt
printscale weekly
[Eliciting Requirements] requires 3 weeks
[Designing Prototype] requires 2 weeks
[Development] requires 8 weeks
[Website Integration] requires 1 weeks
[Call Hold Integration] requires 1 weeks
[Casebook Integration] requires 2 weeks
[Testing] requires 3 weeks
[Adviser Training] requires 1 weeks

[Eliciting Requirements] -> [Designing Prototype]
[Designing Prototype] -> [Development]
[Development] -> [Website Integration]
[Development] -> [Call Hold Integration]
[Call Hold Integration] -> [Casebook Integration]
[Casebook Integration] -> [Testing]
[Testing] -> [Adviser Training]

@endgantt